### ISSUE TITLE
Error messages are printed to standard output

### ISSUE THREAD

**Issue by HarryCutts** [Novatek-MSP/NT36XXX_CMDLINE_TOOL#1]
Error messages from the bridge tool (Bdg_Cmd_M252) are being printed to standard output, not standard error. That results in the error messages getting included in the reported firmware version (e.g. when I reset the device in the middle of bridge FW update, on the next boot `bridge_dev_fw_ver` was "Error : Device is not in aprom, set version to 0#012#0120", when it should just have been "0").

To fix this, you just need to modify [your `PE` macro](https://github.com/Novatek-MSP/chromeos-nvt-touch-updater/blob/1643bc7112ca2c19e51d67218b892ef2acf370c7/Bridge.c#L60) to print to standard error (e.g. using `fprintf(stderr, ...)` instead of `printf(...)`).

**Comment by Novatek-MSP** [comment]
This should be resolved in 1.0.6
